services:
  builder:
    image: gradle:7.6.0-jdk17
    container_name: travlog_backend_builder
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["./gradlew", "clean", "bootJar", "--no-daemon"]
    # Stop the builder container once the build completes
    restart: "no"
    # Prevent `builder` from being run automatically with `docker-compose up`
    labels:
      com.docker.compose.oneoff: "true"
    
  backend:
    image: eclipse-temurin:17-jre-alpine
    container_name: travlog_backend_runtime
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      # Mount only the JAR file from the build step
      - ./backend/build/libs/app.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: travlog_mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3366:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      - ./db/init.sh:/docker-entrypoint-initdb.d/00-init.sh # Custom script for migrations and seed data

volumes:
  db_data: